# Use the official lightweight Python image
FROM python:3.11-slim



ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_NAME=ucare
ENV DB_USER=admin123
ENV DB_PASSWORD=admin123

# Set the working directory
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . /app

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
